### ISSUE TITLE
Index Queries

### ISSUE THREAD

**Issue by rkamun1** [mrvautin/wee-db#1]
Hi,

Thanks so much for this wonderful implementation of `lowdb`. I'm trying to figure out how to execute a `get`to return all records in the database. I have tried a couple of implementations, but still haven't managed to execute it. I've tried the following to no avail:

`db._get('stories').value();`
`db.get('stories').value();`

All the errors calls state that `TypeError: xxxx is not a function` eg `TypeError: db._get is not a function`

How do I implement the `lowdb` calls?

my server looks like this

```const express = require('express');
var bodyParser = require('body-parser')

var wee_db = require('wee-db');
var db = wee_db('db.json')
var cors = require('cors')
var app = express()

app.use(bodyParser());
app.use(cors())```

Thanks for all your help.

**Comment by mrvautin** [comment]
You can only use `._find` from `lowdb`. Have you tried using `._find`?
